server:
  port: 80

spring:
  application:
    name: jwks-prod

management:
  server:
    port: 15020
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
