server:
  port: 80

spring:
  application:
    name: jwks-prod

management:
  endpoints:
    web:
      exposure:
        include: health,liveness,readiness
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
